name: Generate Files and Raise PR

on: workflow_dispatch


permissions:
  contents: write
  pull-requests: write


jobs:
  generate_and_raise_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Pip
        working-directory: ./auto-add-new-versions
        run: pip install -r requirements.txt
      
      - name: Check if new versions available
        id: check-versions
        run: |
          python auto-add-new-versions/check-for-new-versions.py
          echo $PR_TITLE
          echo $NEW_VERSIONS
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
          echo "NEW_VERSIONS=$NEW_VERSIONS" >> $GITHUB_ENV
        env:
          EXCLUDED_VERSIONS: ${{ vars.EXCLUDED_VERSIONS }}
      
      - name: echo PR title
        run: |
          echo ${{env.PR_TITLE}}
          echo ${{env.NEW_VERSIONS}}
